/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const MINUTES = BigInt("60000");
export const COLLECTION_SIZE = BigInt("10000");
export const AUCTION_START_PRICE = BigInt("1000000000000000000");
export const AUCTION_END_PRICE = BigInt("100000000000000000");
export const AUCTION_TIME = BigInt("600000");
export const AUCTION_DROP_INTERVAL = BigInt("60000");
export const AUCTION_DROP_PER_STEP = BigInt("90000000000000000");
