/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as PaymentSplitContractJson } from "../PaymentSplit.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace PaymentSplitTypes {
  export type Fields = {
    numPayees: bigint;
    owner: Address;
    paused: boolean;
    numPayeesRegistered: bigint;
    totalShares: bigint;
    totalReleased: bigint;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type PayeeAddedEvent = ContractEvent<{
    account: Address;
    shares: bigint;
  }>;
  export type PaymentReleasedEvent = ContractEvent<{
    to: Address;
    amount: bigint;
  }>;
  export type PaymentReceivedEvent = ContractEvent<{
    from: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    receive: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    addPayee: {
      params: CallContractParams<{ account: Address; shares: bigint }>;
      result: CallContractResult<null>;
    };
    release: {
      params: CallContractParams<{ account: Address }>;
      result: CallContractResult<null>;
    };
    releasable: {
      params: CallContractParams<{ account: Address }>;
      result: CallContractResult<bigint>;
    };
    pendingPayment: {
      params: CallContractParams<{
        account: Address;
        totalReceived: bigint;
        alreadyReleased: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    updateShares: {
      params: CallContractParams<{ account: Address; shares: bigint }>;
      result: CallContractResult<null>;
    };
    updateOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    pause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    unpause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    receive: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    addPayee: {
      params: SignExecuteContractMethodParams<{
        account: Address;
        shares: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    release: {
      params: SignExecuteContractMethodParams<{ account: Address }>;
      result: SignExecuteScriptTxResult;
    };
    releasable: {
      params: SignExecuteContractMethodParams<{ account: Address }>;
      result: SignExecuteScriptTxResult;
    };
    pendingPayment: {
      params: SignExecuteContractMethodParams<{
        account: Address;
        totalReceived: bigint;
        alreadyReleased: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    updateShares: {
      params: SignExecuteContractMethodParams<{
        account: Address;
        shares: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    updateOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    pause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    unpause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = {
    sharesMap?: Map<Address, bigint>;
    releasedMap?: Map<Address, bigint>;
  };
}

class Factory extends ContractFactory<
  PaymentSplitInstance,
  PaymentSplitTypes.Fields
> {
  encodeFields(fields: PaymentSplitTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { PayeeAdded: 0, PaymentReleased: 1, PaymentReceived: 2 };
  consts = {
    ErrorCodes: {
      InvalidShares: BigInt("1"),
      AccountHasShares: BigInt("2"),
      AccountHasNoShares: BigInt("3"),
      AccountIsNotDuePayment: BigInt("4"),
      InvalidSetup: BigInt("5"),
      NotAuthorized: BigInt("6"),
      Paused: BigInt("7"),
    },
  };

  at(address: string): PaymentSplitInstance {
    return new PaymentSplitInstance(address);
  }

  tests = {
    receive: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { amount: bigint },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "receive", params, getContractByCodeHash);
    },
    addPayee: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { account: Address; shares: bigint },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "addPayee", params, getContractByCodeHash);
    },
    release: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { account: Address },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "release", params, getContractByCodeHash);
    },
    releasable: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { account: Address },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<bigint, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "releasable", params, getContractByCodeHash);
    },
    pendingPayment: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { account: Address; totalReceived: bigint; alreadyReleased: bigint },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<bigint, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "pendingPayment", params, getContractByCodeHash);
    },
    updateShares: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { account: Address; shares: bigint },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "updateShares", params, getContractByCodeHash);
    },
    updateOwner: async (
      params: TestContractParams<
        PaymentSplitTypes.Fields,
        { newOwner: Address },
        PaymentSplitTypes.Maps
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "updateOwner", params, getContractByCodeHash);
    },
    pause: async (
      params: Omit<
        TestContractParams<
          PaymentSplitTypes.Fields,
          never,
          PaymentSplitTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "pause", params, getContractByCodeHash);
    },
    unpause: async (
      params: Omit<
        TestContractParams<
          PaymentSplitTypes.Fields,
          never,
          PaymentSplitTypes.Maps
        >,
        "testArgs"
      >
    ): Promise<TestContractResult<null, PaymentSplitTypes.Maps>> => {
      return testMethod(this, "unpause", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: PaymentSplitTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: PaymentSplitTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const PaymentSplit = new Factory(
  Contract.fromJson(
    PaymentSplitContractJson,
    "=10-6+c6=2-2=1-1=1-1=2-2+75=2-1=1+0=1-3+22b=2+4=2+256426b=94-2+35=126+7a7e0214696e73657274206174206d617020706174683a2000=12+1601a0037e03086265666f72653a20022c2000=14+1601a0037e030761667465723a20022c2000=473-1+4=102+1=1-1=52+7a7e021472656d6f7665206174206d617020706174683a2000=186",
    "c059aa4d1e233716dca31cc85ad0ff7cfcc474494beefac1c37a6b980fc74b09",
    []
  )
);
registerContract(PaymentSplit);

// Use this class to interact with the blockchain
export class PaymentSplitInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    sharesMap: new RalphMap<Address, bigint>(
      PaymentSplit.contract,
      this.contractId,
      "sharesMap"
    ),
    releasedMap: new RalphMap<Address, bigint>(
      PaymentSplit.contract,
      this.contractId,
      "releasedMap"
    ),
  };

  async fetchState(): Promise<PaymentSplitTypes.State> {
    return fetchContractState(PaymentSplit, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribePayeeAddedEvent(
    options: EventSubscribeOptions<PaymentSplitTypes.PayeeAddedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PaymentSplit.contract,
      this,
      options,
      "PayeeAdded",
      fromCount
    );
  }

  subscribePaymentReleasedEvent(
    options: EventSubscribeOptions<PaymentSplitTypes.PaymentReleasedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PaymentSplit.contract,
      this,
      options,
      "PaymentReleased",
      fromCount
    );
  }

  subscribePaymentReceivedEvent(
    options: EventSubscribeOptions<PaymentSplitTypes.PaymentReceivedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PaymentSplit.contract,
      this,
      options,
      "PaymentReceived",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | PaymentSplitTypes.PayeeAddedEvent
      | PaymentSplitTypes.PaymentReleasedEvent
      | PaymentSplitTypes.PaymentReceivedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      PaymentSplit.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    receive: async (
      params: PaymentSplitTypes.CallMethodParams<"receive">
    ): Promise<PaymentSplitTypes.CallMethodResult<"receive">> => {
      return callMethod(
        PaymentSplit,
        this,
        "receive",
        params,
        getContractByCodeHash
      );
    },
    addPayee: async (
      params: PaymentSplitTypes.CallMethodParams<"addPayee">
    ): Promise<PaymentSplitTypes.CallMethodResult<"addPayee">> => {
      return callMethod(
        PaymentSplit,
        this,
        "addPayee",
        params,
        getContractByCodeHash
      );
    },
    release: async (
      params: PaymentSplitTypes.CallMethodParams<"release">
    ): Promise<PaymentSplitTypes.CallMethodResult<"release">> => {
      return callMethod(
        PaymentSplit,
        this,
        "release",
        params,
        getContractByCodeHash
      );
    },
    releasable: async (
      params: PaymentSplitTypes.CallMethodParams<"releasable">
    ): Promise<PaymentSplitTypes.CallMethodResult<"releasable">> => {
      return callMethod(
        PaymentSplit,
        this,
        "releasable",
        params,
        getContractByCodeHash
      );
    },
    pendingPayment: async (
      params: PaymentSplitTypes.CallMethodParams<"pendingPayment">
    ): Promise<PaymentSplitTypes.CallMethodResult<"pendingPayment">> => {
      return callMethod(
        PaymentSplit,
        this,
        "pendingPayment",
        params,
        getContractByCodeHash
      );
    },
    updateShares: async (
      params: PaymentSplitTypes.CallMethodParams<"updateShares">
    ): Promise<PaymentSplitTypes.CallMethodResult<"updateShares">> => {
      return callMethod(
        PaymentSplit,
        this,
        "updateShares",
        params,
        getContractByCodeHash
      );
    },
    updateOwner: async (
      params: PaymentSplitTypes.CallMethodParams<"updateOwner">
    ): Promise<PaymentSplitTypes.CallMethodResult<"updateOwner">> => {
      return callMethod(
        PaymentSplit,
        this,
        "updateOwner",
        params,
        getContractByCodeHash
      );
    },
    pause: async (
      params?: PaymentSplitTypes.CallMethodParams<"pause">
    ): Promise<PaymentSplitTypes.CallMethodResult<"pause">> => {
      return callMethod(
        PaymentSplit,
        this,
        "pause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    unpause: async (
      params?: PaymentSplitTypes.CallMethodParams<"unpause">
    ): Promise<PaymentSplitTypes.CallMethodResult<"unpause">> => {
      return callMethod(
        PaymentSplit,
        this,
        "unpause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    receive: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"receive">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"receive">> => {
      return signExecuteMethod(PaymentSplit, this, "receive", params);
    },
    addPayee: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"addPayee">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"addPayee">> => {
      return signExecuteMethod(PaymentSplit, this, "addPayee", params);
    },
    release: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"release">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"release">> => {
      return signExecuteMethod(PaymentSplit, this, "release", params);
    },
    releasable: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"releasable">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"releasable">> => {
      return signExecuteMethod(PaymentSplit, this, "releasable", params);
    },
    pendingPayment: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"pendingPayment">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"pendingPayment">> => {
      return signExecuteMethod(PaymentSplit, this, "pendingPayment", params);
    },
    updateShares: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"updateShares">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"updateShares">> => {
      return signExecuteMethod(PaymentSplit, this, "updateShares", params);
    },
    updateOwner: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"updateOwner">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"updateOwner">> => {
      return signExecuteMethod(PaymentSplit, this, "updateOwner", params);
    },
    pause: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"pause">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"pause">> => {
      return signExecuteMethod(PaymentSplit, this, "pause", params);
    },
    unpause: async (
      params: PaymentSplitTypes.SignExecuteMethodParams<"unpause">
    ): Promise<PaymentSplitTypes.SignExecuteMethodResult<"unpause">> => {
      return signExecuteMethod(PaymentSplit, this, "unpause", params);
    },
  };

  async multicall<Calls extends PaymentSplitTypes.MultiCallParams>(
    calls: Calls
  ): Promise<PaymentSplitTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends PaymentSplitTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<PaymentSplitTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | PaymentSplitTypes.MultiCallParams
      | PaymentSplitTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      PaymentSplit,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
